spring:

  main:
    web-application-type: reactive

  application:
    name: GATEWAY-MODULE
    
  cloud:
    gateway: 
    
      #globalcors:
        #corsConfigurations:
          #'[/**]':
            #allowedOrigins: "http://localhost:4200"
            #allowedMethods:
            #- GET
            #- POST
            #- PUT
            #- PATCH
            #allowed-headers:
              #- content-type
      
      routes:
        - id: user-module
          uri: lb://USER-MODULE
          predicates:
          - Path=/user/**
        - id: admin-module
          uri: lb://ADMIN-MODULE
          predicates:
          - Path=/admin/**
          
      
    
server:
  port: 7000
  
eureka:
   client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka
   instance:
      hostname: localhost
      

